run:
	python genwann.py

clean:
	-rm assigned_basis.txt Downfold.json Downfolded_hr.nc Downfolded_hr.txt

distclean:
	-rm assigned_basis.txt Downfold.json Downfolded_hr.nc Downfolded_hr.txt Downfolded_wannier_hr.dat *.png *.svg *.pdf
